#clone projcert
#install docker-compose
#run docker-compose

--- #install jenkins
- hosts: projcert_server
  name: projcert install 
  become: yes
  gather_facts: no
  tasks:
    - name: Install docker-compose
      apt:
        pkg: 
          - docker-compose
        state: present

    - name: stopping projcert
      shell: "docker-compose down"
      args:
        chdir: /home/ubuntu/project1/
    
    - name: running projcert
      shell: "docker-compose up -d"
      args:
        chdir: /home/ubuntu/project1/

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/Ayushchandra2811/projCert.git'
        dest: /home/ubuntu/project1
  

    # - name: Update all packages to their latest version
    #   apt:
    #     name: "*"
    #     update_cache: yes
    #     state: latest

   
    - name: running projcert
      shell: "docker-compose up -d"
      args:
        chdir: /home/ubuntu/project1/
