---
- hosts: jenkins
  name: uninstall jenkins on server
  become: yes
  
  tasks:
    - name: uninstall jenkins
      apt:
      shell: sudo apt-get remove --purge jenkins
        pkg: 
          - openjdk-8-jdk
          - jenkins
        state: absent
